DROP TABLE IF EXISTS STATION;

CREATE TABLE STATION (
  station_id VARCHAR(256) PRIMARY KEY,
  name VARCHAR(256) NOT NULL,
  call_sign VARCHAR(256) NOT NULL,
  hd_enabled BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE INDEX name_idx ON STATION(name);
CREATE INDEX hd_idx ON STATION(hd_enabled);